# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlsysops-cms-app
  namespace: mlsysops-cms-canary

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mlsysops-cms-app
  template:
    metadata:
      labels:
        app: mlsysops-cms-app
    spec:
      containers:
        - name: mlsysops-cms-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MODEL_STAGE
              value: "{{ .Values.env.modelStage }}"
            - name: MLFLOW_TRACKING_URI
              value: "{{ .Values.env.mlflowTrackingUri }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: mlsysops-cms-app
  namespace: mlsysops-cms-canary
spec:
  selector:
    app: mlsysops-cms-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
  externalIPs:
    - {{ .Values.service.externalIP }}

