---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: mlsysops-cms-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "mlflowdb"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          hostPath:
            path: /mnt/chameleon-block/postgres-data
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: mlsysops-cms-platform
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
