- name: Apply Chameleon credentials secret using kubectl
  become: yes
  vars_files:
    - secrets.yml
  shell: |
    cat <<EOF | kubectl apply -f -
    apiVersion: v1
    kind: Secret
    metadata:
      name: chameleon-credentials
      namespace: mlsysops-cms-platform
    type: Opaque
    stringData:
      accesskey: "{{ chameleon_access_key }}"
      secretkey: "{{ chameleon_secret_key }}"
    EOF
