- name: Format and mount Chameleon block storage
  hosts: node1
  become: yes
  tasks:

    - name: Create mount point
      file:
        path: /mnt/postgres-data
        state: directory
        mode: '0755'

    - name: Format /dev/vdb as ext4 (if unformatted)
      filesystem:
        fstype: ext4
        dev: /dev/vdb
      when: ansible_devices.vdb is defined

    - name: Mount and persist /dev/vdb to /mnt/postgres-data
      mount:
        path: /mnt/postgres-data
        src: /dev/vdb
        fstype: ext4
        opts: defaults
        state: mounted  # Ensures it's mounted AND written to /etc/fstab
