- hosts: master
  become: yes
  tasks:
    - name: Initialize the cluster
      command: sudo kubeadm init --apiserver-advertise-address={{ ansible_host }} --pod-network-cidr=10.244.0.0/16
      args:
        chdir: /home/cc
      register: init_output
      ignore_errors: true

    - name: Save output to log file
      copy:
        content: "{{ init_output.stdout }}\n{{ init_output.stderr }}"
        dest: /home/cc/cluster_initialized.log

    - name: Create .kube directory
      become: yes
      become_user: cc
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: Copy admin.conf to User's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/cc/.kube/config
        remote_src: yes
        owner: cc

- name: Configure and apply Flannel
  hosts: master
  become: true
  tasks:
    - name: Apply Flannel
      shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Get specific interface used to reach
      shell: ip -o addr show | awk -v ip="{{ ansible_host }}" '$0 ~ ip {print $2}'
      register: iface_result
      changed_when: false

    - name: Show interface
      debug:
        msg: "Interface for {{ ansible_host }} is {{ iface_result.stdout }}"

    - name: Patch Flannel to use interface
      shell: |
        kubectl -n kube-flannel patch daemonset kube-flannel-ds \
          --type='json' \
          -p='[{"op":"add","path":"/spec/template/spec/containers/0/args/-","value":"--iface={{ iface_result.stdout }}"}]'
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf