apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: kaniko-pvc-build-
spec:
  entrypoint: kaniko-dag
  volumes:
    - name: workdir
      emptyDir: {}
    - name: workdir-app
      emptyDir: {}

  templates:
    - name: kaniko-dag
      parallelism: 8
      dag:
        tasks:
          # Clone repos (in parallel)
          - name: clone-app-repo
            template: app-git-clone

          - name: clone-pipeline-repo
            template: pipeline-git-clone

          # Conditionally build (parallel)
          - name: kaniko-build-app
            template: kaniko-app
            dependencies: [clone-app-repo]

          - name: kaniko-build-train
            template: kaniko-train
            dependencies: [clone-pipeline-repo]

          - name: kaniko-build-eval
            template: kaniko-eval
            dependencies: [clone-pipeline-repo]

          - name: kaniko-build-data
            template: kaniko-data
            dependencies: [clone-pipeline-repo]
          
          - name: kaniko-build-optimize
            template: kaniko-optimize
            dependencies: [clone-pipeline-repo]

    - name: app-git-clone
      nodeSelector:
        kubernetes.io/hostname: node2-mlops-project26-gk2657
      container:
        image: alpine/git
        command: [sh, -c]
        args:
          - |
            git clone --branch main https://github.com/gauravkuwar/mlsysops-cms-app.git /mnt/workspace-app
        volumeMounts:
          - name: workdir-app
            mountPath: /mnt/workspace-app

    - name: pipeline-git-clone
      nodeSelector:
        kubernetes.io/hostname: node3-mlops-project26-gk2657
      container:
        image: alpine/git
        command: [sh, -c]
        args:
          - |
            git clone --branch main https://github.com/gauravkuwar/mlsysops-cms-pipeline.git /mnt/workspace
        volumeMounts:
          - name: workdir
            mountPath: /mnt/workspace

    - name: kaniko-app
      nodeSelector:
        kubernetes.io/hostname: node2-mlops-project26-gk2657
      container:
        image: gcr.io/kaniko-project/executor:latest
        command: ["/kaniko/executor"]
        args:
          - --dockerfile=Dockerfile
          - --context=/mnt/workspace-app
          - --destination=registry.kube-system.svc.cluster.local:5000/mlsysops-cms-app:production-latest
          - --destination=registry.kube-system.svc.cluster.local:5000/mlsysops-cms-app:staging-latest
          - --destination=registry.kube-system.svc.cluster.local:5000/mlsysops-cms-app:canary-latest
          - --cache=true
          - --cache-repo=registry.kube-system.svc.cluster.local:5000/kaniko-cache
          - --cache-copy-layers
          - --compressed-caching
          - --insecure
        volumeMounts:
          - name: workdir-app
            mountPath: /mnt/workspace-app

    - name: kaniko-train
      nodeSelector:
        kubernetes.io/hostname: node3-mlops-project26-gk2657
      container:
        image: gcr.io/kaniko-project/executor:latest
        command: ["/kaniko/executor"]
        args:
          - --dockerfile=Dockerfile
          - --context=/mnt/workspace/train
          - --destination=registry.kube-system.svc.cluster.local:5000/mlsysops-cms-train:latest
          - --cache=true
          - --cache-repo=registry.kube-system.svc.cluster.local:5000/kaniko-cache
          - --cache-copy-layers
          - --compressed-caching
          - --insecure
        volumeMounts:
          - name: workdir
            mountPath: /mnt/workspace

    - name: kaniko-eval
      nodeSelector:
          kubernetes.io/hostname: node3-mlops-project26-gk2657
      container:
        image: gcr.io/kaniko-project/executor:latest
        command: ["/kaniko/executor"]
        args:
          - --dockerfile=Dockerfile
          - --context=/mnt/workspace/eval
          - --destination=registry.kube-system.svc.cluster.local:5000/mlsysops-cms-eval:latest
          - --cache=true
          - --cache-repo=registry.kube-system.svc.cluster.local:5000/kaniko-cache
          - --cache-copy-layers
          - --compressed-caching
          - --insecure
        volumeMounts:
          - name: workdir
            mountPath: /mnt/workspace

    - name: kaniko-data
      nodeSelector:
          kubernetes.io/hostname: node3-mlops-project26-gk2657
      container:
        image: gcr.io/kaniko-project/executor:latest
        command: ["/kaniko/executor"]
        args:
          - --dockerfile=Dockerfile
          - --context=/mnt/workspace/data
          - --destination=registry.kube-system.svc.cluster.local:5000/mlsysops-cms-data:latest
          - --cache=true
          - --cache-repo=registry.kube-system.svc.cluster.local:5000/kaniko-cache
          - --cache-copy-layers
          - --compressed-caching
          - --insecure
        volumeMounts:
          - name: workdir
            mountPath: /mnt/workspace

    - name: kaniko-optimize
      nodeSelector:
        kubernetes.io/hostname: node3-mlops-project26-gk2657
      container:
        image: gcr.io/kaniko-project/executor:latest
        command: ["/kaniko/executor"]
        args:
          - --dockerfile=Dockerfile
          - --context=/mnt/workspace/optimize
          - --destination=registry.kube-system.svc.cluster.local:5000/mlsysops-cms-optimize:latest
          - --cache=true
          - --cache-repo=registry.kube-system.svc.cluster.local:5000/kaniko-cache
          - --cache-copy-layers
          - --compressed-caching
          - --insecure
        volumeMounts:
          - name: workdir
            mountPath: /mnt/workspace