apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: kaniko-pvc-build-
spec:
  entrypoint: kaniko-build-flow
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: workdir-app
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

  templates:

    - name: kaniko-build-flow
      steps:
        - - name: clone-app-repo
            template: app-git-clone
        - - name: clone-pipeline-repo
            template: pipeline-git-clone

        - - name: check-app-image
            template: check-image
            arguments:
              parameters:
                - name: image
                  value: "mlsysops-cms-app"
                - name: sha
                  value: "{{steps.clone-app-repo.outputs.parameters.sha}}"
        - - name: kaniko-build-app
            template: kaniko-app
            when: "{{steps.check-app-image.outputs.parameters.exists}} == false"
            arguments:
              parameters:
                - name: sha
                  value: "{{steps.clone-app-repo.outputs.parameters.sha}}"

        - - name: check-train-image
            template: check-image
            arguments:
              parameters:
                - name: image
                  value: "mlsysops-cms-train"
                - name: sha
                  value: "{{steps.clone-pipeline-repo.outputs.parameters.train-sha}}"
        - - name: kaniko-build-train
            template: kaniko-train
            when: "{{steps.check-train-image.outputs.parameters.exists}} == false"
            arguments:
              parameters:
                - name: sha
                  value: "{{steps.clone-pipeline-repo.outputs.parameters.train-sha}}"

        - - name: check-eval-image
            template: check-image
            arguments:
              parameters:
                - name: image
                  value: "mlsysops-cms-eval"
                - name: sha
                  value: "{{steps.clone-pipeline-repo.outputs.parameters.eval-sha}}"
        - - name: kaniko-build-eval
            template: kaniko-eval
            when: "{{steps.check-eval-image.outputs.parameters.exists}} == false"
            arguments:
              parameters:
                - name: sha
                  value: "{{steps.clone-pipeline-repo.outputs.parameters.eval-sha}}"
                  
    - name: check-image
      inputs:
        parameters:
          - name: image
          - name: sha
      outputs:
        parameters:
          - name: exists
            valueFrom:
              path: /tmp/image-exists.txt
      script:
        image: curlimages/curl
        command: [sh]
        source: |
          IMAGE_URL="http://registry.kube-system.svc.cluster.local:5000/v2/{{inputs.parameters.image}}/manifests/{{inputs.parameters.sha}}"
          echo "Checking if image exists at $IMAGE_URL"
          code=$(curl --insecure -s -o /dev/null -w "%{http_code}" -H "Accept: application/vnd.docker.distribution.manifest.v2+json" "$IMAGE_URL")
          if [ "$code" -eq 200 ]; then
            echo "true" > /tmp/image-exists.txt
          else
            echo "false" > /tmp/image-exists.txt
          fi

    - name: app-git-clone
      outputs:
        parameters:
          - name: sha
            valueFrom:
              path: /mnt/workspace-app/sha.txt
      container:
        image: alpine/git
        command: [sh, -c]
        args:
          - |
            git clone --branch main https://github.com/gauravkuwar/mlsysops-cms-app.git /mnt/workspace-app
            cd /mnt/workspace-app && git rev-parse --short HEAD > sha.txt
        volumeMounts:
          - name: workdir-app
            mountPath: /mnt/workspace-app

    - name: pipeline-git-clone
      outputs:
        parameters:
          - name: train-sha
            valueFrom:
              path: /mnt/workspace/train/train_sha.txt
          - name: eval-sha
            valueFrom:
              path: /mnt/workspace/eval/eval_sha.txt
      container:
        image: alpine/git
        command: [sh, -c]
        args:
          - |
            git clone --branch main https://github.com/gauravkuwar/mlsysops-cms-pipeline.git /mnt/workspace
            cd /mnt/workspace/train && git log -n1 --pretty=format:%h > train_sha.txt
            cd /mnt/workspace/eval && git log -n1 --pretty=format:%h > eval_sha.txt
        volumeMounts:
          - name: workdir
            mountPath: /mnt/workspace

    - name: kaniko-app
      inputs:
        parameters:
          - name: sha
      container:
        image: gcr.io/kaniko-project/executor:latest
        command: ["/kaniko/executor"]
        args:
          - --dockerfile=/mnt/workspace-app/Dockerfile
          - --context=/mnt/workspace-app
          - --destination=registry.kube-system.svc.cluster.local:5000/mlsysops-cms-app:{{inputs.parameters.sha}}
          - --destination=registry.kube-system.svc.cluster.local:5000/mlsysops-cms-app:latest
          - --insecure
        volumeMounts:
          - name: workdir-app
            mountPath: /mnt/workspace-app

    - name: kaniko-train
      inputs:
        parameters:
          - name: sha
      container:
        image: gcr.io/kaniko-project/executor:latest
        command: ["/kaniko/executor"]
        args:
          - --dockerfile=/mnt/workspace/train/Dockerfile
          - --context=/mnt/workspace/train
          - --destination=registry.kube-system.svc.cluster.local:5000/mlsysops-cms-train:{{inputs.parameters.sha}}
          - --destination=registry.kube-system.svc.cluster.local:5000/mlsysops-cms-train:latest
          - --insecure
        volumeMounts:
          - name: workdir
            mountPath: /mnt/workspace

    - name: kaniko-eval
      inputs:
        parameters:
          - name: sha
      container:
        image: gcr.io/kaniko-project/executor:latest
        command: ["/kaniko/executor"]
        args:
          - --dockerfile=/mnt/workspace/eval/Dockerfile
          - --context=/mnt/workspace/eval
          - --destination=registry.kube-system.svc.cluster.local:5000/mlsysops-cms-eval:{{inputs.parameters.sha}}
          - --destination=registry.kube-system.svc.cluster.local:5000/mlsysops-cms-eval:latest
          - --insecure
        volumeMounts:
          - name: workdir
            mountPath: /mnt/workspace
