apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: kaniko-pvc-build-
spec:
  entrypoint: kaniko-build-flow
  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi

  - metadata:
      name: workdir-train
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi

  - metadata:
      name: workdir-eval
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi

  templates:
  - name: kaniko-build-flow
    steps:
      - - name: clone-repo
          template: git-clone
      - - name: kaniko-build
          template: kaniko
      - - name: clone-train-repo
          template: train-git-clone
      - - name: kaniko-train-build
          template: kaniko-train
      - - name: clone-eval-repo
          template: eval-git-clone
      - - name: kaniko-eval-build
          template: kaniko-eval

  - name: git-clone
    container:
      image: alpine/git
      command: [sh, -c]
      args:
        - |
          git clone --branch main https://github.com/gauravkuwar/mlsysops-cms-app.git /mnt/workspace
      volumeMounts:
      - name: workdir
        mountPath: /mnt/workspace

  - name: kaniko
    container:
      image: gcr.io/kaniko-project/executor:latest
      args:
        - --dockerfile=/mnt/workspace/Dockerfile
        - --context=/mnt/workspace
        - --destination=registry.kube-system.svc.cluster.local:5000/mlsysops-cms-app:staging-1.0.0
        - --insecure
      volumeMounts:
      - name: workdir
        mountPath: /mnt/workspace

  - name: train-git-clone
    container:
      image: alpine/git
      command: [sh, -c]
      args:
        - |
          git clone --branch main https://github.com/gauravkuwar/mlsysops-cms-train.git /mnt/workspace-train
      volumeMounts:
      - name: workdir-train
        mountPath: /mnt/workspace-train

  - name: kaniko-train
    container:
      image: gcr.io/kaniko-project/executor:latest
      args:
        - --dockerfile=/mnt/workspace-train/Dockerfile
        - --context=/mnt/workspace-train
        - --destination=registry.kube-system.svc.cluster.local:5000/mlsysops-cms-train:latest
        - --insecure
      volumeMounts:
      - name: workdir-train
        mountPath: /mnt/workspace-train

  - name: eval-git-clone
    container:
      image: alpine/git
      command: [sh, -c]
      args:
        - |
          git clone --branch main https://github.com/gauravkuwar/mlsysops-cms-eval.git /mnt/workspace-eval
      volumeMounts:
      - name: workdir-eval
        mountPath: /mnt/workspace-eval

  - name: kaniko-eval
    container:
      image: gcr.io/kaniko-project/executor:latest
      args:
        - --dockerfile=/mnt/workspace-eval/Dockerfile
        - --context=/mnt/workspace-eval
        - --destination=registry.kube-system.svc.cluster.local:5000/mlsysops-cms-eval:latest
        - --insecure
      volumeMounts:
      - name: workdir-eval
        mountPath: /mnt/workspace-eval