apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: mlops-pipeline
spec:
  entrypoint: mlops-dag
  templates:

    - name: mlops-dag
      dag:
        tasks:
          - name: trigger-training
            template: call-train-api

          - name: run-eval
            template: eval-task
            dependencies: [trigger-training]

          - name: run-optimize
            template: optimize-task
            dependencies: [run-eval]

    - name: call-train-api
      container:
        image: curlimages/curl
        command: ["sh", "-c"]
        args:
          - |
            echo "Triggering training endpoint..."
            curl --fail --retry 5 --retry-connrefused -X POST http://mlsysops-cms-train.mlsysops-cms-platform.svc.cluster.local:9090/trigger-training

    - name: eval-task
      container:
        image: registry.kube-system.svc.cluster.local:5000/mlsysops-cms-eval:latest
        env:
          - name: MLFLOW_TRACKING_URI
            value: http://mlflow.mlsysops-cms-platform.svc.cluster.local:8000
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "5Gi"
            cpu: "2000m"
        volumeMounts:
          - name: data-volume
            mountPath: /mnt/data
      volumes:
        - name: data-volume
          hostPath:
            path: /mnt/chameleon-block/data
            type: Directory
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - node1-mlops-project26-gk2657
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
    
    - name: optimize-task
      container:
        image: registry.kube-system.svc.cluster.local:5000/mlsysops-cms-optimize:latest
        env:
          - name: MLFLOW_TRACKING_URI
            value: http://mlflow.mlsysops-cms-platform.svc.cluster.local:8000

