---
- name: Deploy MLflow platform via ArgoCD & Helm
  hosts: node1
  become: yes
  environment:
    KUBECONFIG: /home/cc/.kube/config
  vars:
    argocd_username: "admin"
    repo_path: "https://github.com/gauravkuwar/mlsysops-cms-iac.git"
    app_name: "mlsysops-cms-platform"
    app_path: "k8s/platform"

  tasks:
    - name: Get ArgoCD admin password from Kubernetes secret
      command: >
        kubectl get secret -n argocd argocd-initial-admin-secret \
        -o jsonpath="{.data.password}"
      register: argocd_password_base64

    - name: Decode ArgoCD admin password
      shell: echo {{ argocd_password_base64.stdout }} | base64 --decode
      register: argocd_password

    - name: Log in to ArgoCD
      command: >
        argocd login localhost --username {{ argocd_username }} \
        --password "{{ argocd_password.stdout }}" --grpc-web --port-forward --port-forward-namespace=argocd
      register: login_result
      changed_when: false

    - name: Add repository to ArgoCD
      command: >
        argocd repo add {{ repo_path }} --port-forward --port-forward-namespace=argocd
      register: repo_result
      changed_when: "'Repository already exists' not in repo_result.stderr"

    - name: Detect external IP starting with 10.56
      set_fact:
        external_ip: "{{ ansible_all_ipv4_addresses | select('match', '^10\\.56\\..*') | list | first }}"

    - name: Ensure mlsysops-cms-platform namespace exists
      command: kubectl get namespace mlsysops-cms-platform
      register: ns_check
      failed_when: false
      changed_when: false

    - name: Create mlsysops-cms-platform namespace if missing
      when: ns_check.rc != 0
      command: kubectl create namespace mlsysops-cms-platform

    - name: Check if ArgoCD application exists
      command: >
        argocd app get {{ app_name }} --port-forward --port-forward-namespace=argocd
      register: app_check
      failed_when: false
      changed_when: false

    - name: Create ArgoCD Helm application if it does not exist
      when: app_check.rc != 0
      command: >
        argocd app create {{ app_name }} \
        --repo {{ repo_path }} \
        --path {{ app_path }} \
        --dest-server https://kubernetes.default.svc \
        --dest-namespace "" \
        --helm-set-string mlflow.externalIP={{ external_ip }} \
        --port-forward --port-forward-namespace=argocd \
        --sync-policy automated --self-heal
      register: app_create

    - name: Update ArgoCD Helm application if it exists
      when: app_check.rc == 0
      command: >
        argocd app set {{ app_name }} \
        --dest-namespace "" \
        --helm-set-string mlflow.externalIP={{ external_ip }} \
        --port-forward --port-forward-namespace=argocd
      register: app_update