all:
  children:
    master:
      hosts:
        node1:
          ansible_host: 192.168.1.11
          ansible_user: cc
    workers:
      hosts:
        node2:
          ansible_host: 192.168.1.12
          ansible_user: cc
        node3:
          ansible_host: 192.168.1.13
          ansible_user: cc
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: cc
    ansible_become: true
    ansible_environment:
        KUBECONFIG: /home/cc/.kube/config