replicaCount: 1

image:
  repository: registry.kube-system.svc.cluster.local:5000/mlsysops-cms-app
  tag: canary-latest

service:
  port: 8080
  externalIP: ""   # Placeholder

env:
  modelStage: staging
  mlflowTrackingUri: http://mlflow.mlsysops-cms-platform.svc.cluster.local:8000

resources:
  requests:
    cpu: "250m"     # enough for startup and light inference
    memory: "512Mi"
  limits:
    cpu: "750m"     # handles bursts without starving node
    memory: "1.5Gi"

