replicaCount: 1

image:
  repository: registry.kube-system.svc.cluster.local:5000/mlsysops-cms-app
  tag: canary-latest

service:
  port: 8080
  externalIP: ""   # Placeholder

env:
  modelStage: canary
  mlflowTrackingUri: http://mlflow.mlsysops-cms-platform.svc.cluster.local:8000

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "200m"
    memory: "128Mi"

