replicaCount: 1

image:
  repository: registry.kube-system.svc.cluster.local:5000/mlsysops-cms-app
  tag: production-latest

service:
  port: 80
  externalIP: ""   # Placeholder

env:
  modelStage: development
  mlflowTrackingUri: http://mlflow.mlsysops-cms-platform.svc.cluster.local:8000

resources:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "1.5Gi"

