minio:
  externalIP: "0.0.0.0"

mlflow:
  externalIP: "0.0.0.0"

train:
  replicaCount: 1

  image:
    repository: registry.kube-system.svc.cluster.local:5000/mlsysops-cms-train
    tag: latest

  service:
    port: 9090
    externalIP: ""   # Placeholder

  resources:
    limits:
      cpu: "1000m"
      memory: "1Gi"
    requests:
      cpu: "500m"
      memory: "512Mi"

  env:
    mlflowTrackingUri: http://mlflow.mlsysops-cms-platform.svc.cluster.local:8000