minio:
  externalIP: "0.0.0.0"

mlflow:
  externalIP: "0.0.0.0"

train:
  replicaCount: 1

  image:
    repository: registry.kube-system.svc.cluster.local:5000/mlsysops-cms-train
    tag: staging

  service:
    port: 9090
    externalIP: ""   # Placeholder

  resources:
    limits:
      cpu: "2000m"    # use both vCPUs
      memory: "2Gi"   # safe for model + inference
    requests:
      cpu: "1500m"
      memory: "1Gi"

  env:
    mlflowTrackingUri: http://mlflow.mlsysops-cms-platform.svc.cluster.local:8000